title: Neeno Docs
description: Il manuale per la programmazione di Neeno.
theme: just-the-docs

url: https://gnegnas.github.io/neeno-docs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
